### ISSUE TITLE
Bad token = Internal Error

### ISSUE THREAD

**Issue by padak** [keboola/ex-storage#5] opened 2018-09-24 12:51 UTC
I deleted src bucket (which dropped API token rights). Job in KBC Storage Ex failed with Internal Error instead of "wrong API token rights" or so.

(docker-09fe30f5e0d4da319e090198c8822231)
![image](https://user-images.githubusercontent.com/1427901/45953071-3fa7cb80-c009-11e8-943b-3f0f2d4a9a93.png)

**Comment by odinuv** [comment] 2018-10-03 06:07
duplicate of https://github.com/keboola/ex-storage/issues/2

**Closed** 2018-10-03 06:08 UTC
Labels: bug
